# Python CircleCI 2.0 configuration file
version: 2.1


jobs:
  build:
    macos:
      xcode: 14.3.0 # indicate your selected version of Xcode
    resource_class: macos.m1.large.gen1
    #docker:
      #- image: continuumio/miniconda3

    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies

      # Step 3: run linter and tests
      - run:
          name: run tests
          command: |
            brew install cdo
            brew install nco
            pip install pytest
            pip install coverage
            pip install numpy 
            #pip install cartopy
            pip install rioxarray
            pip install --user codecov
            pip install .
            python testing/test_scripting.py
            coverage run -m pytest tests/test_*.py
            coverage report
            coverage xml
      
           
            
